language: node_js
# default is the very old 0.10.48; use oldest LTS instead
node_js: 12

before_script:
  - npm run lint
  - npm run tsc
script: npm test -- --coverage
after_script:
  # upload coverage reports to CodeCov
  - bash <(curl -s https://codecov.io/bash)
  - npm run test:pub
