name: CI
on: [push, pull_request]
jobs:
  ci:
    name: CI - Node ${{ matrix.node-version }}, ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # LTS Node: https://nodejs.org/en/about/releases/
        os: [ubuntu-latest]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: npm ci

    - name: Build
      run: npm run build
